name: Magisk Test

on:
  workflow_dispatch:

jobs:
  cf_test:
    name: Test on AOSP main Cuttlefish
    runs-on: ubuntu-24.04
    env:
      CF_HOME: /home/runner/aosp_cf_x86_64_phone
    strategy:
      fail-fast: false

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Cuttlefish environment
        run: |
          scripts/cuttlefish.sh setup
          scripts/cuttlefish.sh download

      - name: Run Cuttlefish test
        run: su $USER -c 'scripts/cuttlefish.sh test'

      - name: Upload logs on error
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: "cvd-logs"
          path: |
            /home/runner/aosp_cf_x86_64_phone/cuttlefish/instances/cvd-1/logs
            /home/runner/aosp_cf_x86_64_phone/cuttlefish/instances/cvd-1/cuttlefish_config.json
